// Code generated by protoc-gen-go. DO NOT EDIT.
// source: signrpc/signer.proto

package signrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeyLocator struct {
	/// The family of key being identified.
	KeyFamily int32 `protobuf:"varint,1,opt,name=key_family,json=keyFamily,proto3" json:"key_family,omitempty"`
	/// The precise index of the key being identified.
	KeyIndex             int32    `protobuf:"varint,2,opt,name=key_index,json=keyIndex,proto3" json:"key_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyLocator) Reset()         { *m = KeyLocator{} }
func (m *KeyLocator) String() string { return proto.CompactTextString(m) }
func (*KeyLocator) ProtoMessage()    {}
func (*KeyLocator) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ecd772f6c7ffacf, []int{0}
}

func (m *KeyLocator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyLocator.Unmarshal(m, b)
}
func (m *KeyLocator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyLocator.Marshal(b, m, deterministic)
}
func (m *KeyLocator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyLocator.Merge(m, src)
}
func (m *KeyLocator) XXX_Size() int {
	return xxx_messageInfo_KeyLocator.Size(m)
}
func (m *KeyLocator) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyLocator.DiscardUnknown(m)
}

var xxx_messageInfo_KeyLocator proto.InternalMessageInfo

func (m *KeyLocator) GetKeyFamily() int32 {
	if m != nil {
		return m.KeyFamily
	}
	return 0
}

func (m *KeyLocator) GetKeyIndex() int32 {
	if m != nil {
		return m.KeyIndex
	}
	return 0
}

type KeyDescriptor struct {
	//*
	//The raw bytes of the key being identified. Either this or the KeyLocator
	//must be specified.
	RawKeyBytes []byte `protobuf:"bytes,1,opt,name=raw_key_bytes,json=rawKeyBytes,proto3" json:"raw_key_bytes,omitempty"`
	//*
	//The key locator that identifies which key to use for signing. Either this
	//or the raw bytes of the target key must be specified.
	KeyLoc               *KeyLocator `protobuf:"bytes,2,opt,name=key_loc,json=keyLoc,proto3" json:"key_loc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *KeyDescriptor) Reset()         { *m = KeyDescriptor{} }
func (m *KeyDescriptor) String() string { return proto.CompactTextString(m) }
func (*KeyDescriptor) ProtoMessage()    {}
func (*KeyDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ecd772f6c7ffacf, []int{1}
}

func (m *KeyDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyDescriptor.Unmarshal(m, b)
}
func (m *KeyDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyDescriptor.Marshal(b, m, deterministic)
}
func (m *KeyDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyDescriptor.Merge(m, src)
}
func (m *KeyDescriptor) XXX_Size() int {
	return xxx_messageInfo_KeyDescriptor.Size(m)
}
func (m *KeyDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_KeyDescriptor proto.InternalMessageInfo

func (m *KeyDescriptor) GetRawKeyBytes() []byte {
	if m != nil {
		return m.RawKeyBytes
	}
	return nil
}

func (m *KeyDescriptor) GetKeyLoc() *KeyLocator {
	if m != nil {
		return m.KeyLoc
	}
	return nil
}

type TxOut struct {
	/// The value of the output being spent.
	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	/// The script of the output being spent.
	PkScript             []byte   `protobuf:"bytes,2,opt,name=pk_script,json=pkScript,proto3" json:"pk_script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxOut) Reset()         { *m = TxOut{} }
func (m *TxOut) String() string { return proto.CompactTextString(m) }
func (*TxOut) ProtoMessage()    {}
func (*TxOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ecd772f6c7ffacf, []int{2}
}

func (m *TxOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOut.Unmarshal(m, b)
}
func (m *TxOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOut.Marshal(b, m, deterministic)
}
func (m *TxOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOut.Merge(m, src)
}
func (m *TxOut) XXX_Size() int {
	return xxx_messageInfo_TxOut.Size(m)
}
func (m *TxOut) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOut.DiscardUnknown(m)
}

var xxx_messageInfo_TxOut proto.InternalMessageInfo

func (m *TxOut) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TxOut) GetPkScript() []byte {
	if m != nil {
		return m.PkScript
	}
	return nil
}

type SignDescriptor struct {
	//*
	//A descriptor that precisely describes *which* key to use for signing. This
	//may provide the raw public key directly, or require the Signer to re-derive
	//the key according to the populated derivation path.
	KeyDesc *KeyDescriptor `protobuf:"bytes,1,opt,name=key_desc,json=keyDesc,proto3" json:"key_desc,omitempty"`
	//*
	//A scalar value that will be added to the private key corresponding to the
	//above public key to obtain the private key to be used to sign this input.
	//This value is typically derived via the following computation:
	//
	// derivedKey = privkey + sha256(perCommitmentPoint || pubKey) mod N
	SingleTweak []byte `protobuf:"bytes,2,opt,name=single_tweak,json=singleTweak,proto3" json:"single_tweak,omitempty"`
	//*
	//A private key that will be used in combination with its corresponding
	//private key to derive the private key that is to be used to sign the target
	//input. Within the Lightning protocol, this value is typically the
	//commitment secret from a previously revoked commitment transaction. This
	//value is in combination with two hash values, and the original private key
	//to derive the private key to be used when signing.
	//
	// k = (privKey*sha256(pubKey || tweakPub) +
	//tweakPriv*sha256(tweakPub || pubKey)) mod N
	DoubleTweak []byte `protobuf:"bytes,3,opt,name=double_tweak,json=doubleTweak,proto3" json:"double_tweak,omitempty"`
	//*
	//The full script required to properly redeem the output.  This field will
	//only be populated if a p2wsh or a p2sh output is being signed.
	WitnessScript []byte `protobuf:"bytes,4,opt,name=witness_script,json=witnessScript,proto3" json:"witness_script,omitempty"`
	//*
	//A description of the output being spent. The value and script MUST be provided.
	Output *TxOut `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	//*
	//The target sighash type that should be used when generating the final
	//sighash, and signature.
	Sighash uint32 `protobuf:"varint,7,opt,name=sighash,proto3" json:"sighash,omitempty"`
	//*
	//The target input within the transaction that should be signed.
	InputIndex           int32    `protobuf:"varint,8,opt,name=input_index,json=inputIndex,proto3" json:"input_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignDescriptor) Reset()         { *m = SignDescriptor{} }
func (m *SignDescriptor) String() string { return proto.CompactTextString(m) }
func (*SignDescriptor) ProtoMessage()    {}
func (*SignDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ecd772f6c7ffacf, []int{3}
}

func (m *SignDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignDescriptor.Unmarshal(m, b)
}
func (m *SignDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignDescriptor.Marshal(b, m, deterministic)
}
func (m *SignDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignDescriptor.Merge(m, src)
}
func (m *SignDescriptor) XXX_Size() int {
	return xxx_messageInfo_SignDescriptor.Size(m)
}
func (m *SignDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_SignDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_SignDescriptor proto.InternalMessageInfo

func (m *SignDescriptor) GetKeyDesc() *KeyDescriptor {
	if m != nil {
		return m.KeyDesc
	}
	return nil
}

func (m *SignDescriptor) GetSingleTweak() []byte {
	if m != nil {
		return m.SingleTweak
	}
	return nil
}

func (m *SignDescriptor) GetDoubleTweak() []byte {
	if m != nil {
		return m.DoubleTweak
	}
	return nil
}

func (m *SignDescriptor) GetWitnessScript() []byte {
	if m != nil {
		return m.WitnessScript
	}
	return nil
}

func (m *SignDescriptor) GetOutput() *TxOut {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *SignDescriptor) GetSighash() uint32 {
	if m != nil {
		return m.Sighash
	}
	return 0
}

func (m *SignDescriptor) GetInputIndex() int32 {
	if m != nil {
		return m.InputIndex
	}
	return 0
}

type TxSigHashes struct {
	HashPrevOuts         []byte   `protobuf:"bytes,1,opt,name=hash_prev_outs,json=hashPrevOuts,proto3" json:"hash_prev_outs,omitempty"`
	HashSequence         []byte   `protobuf:"bytes,2,opt,name=hash_sequence,json=hashSequence,proto3" json:"hash_sequence,omitempty"`
	HashOutputs          []byte   `protobuf:"bytes,3,opt,name=hash_outputs,json=hashOutputs,proto3" json:"hash_outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxSigHashes) Reset()         { *m = TxSigHashes{} }
func (m *TxSigHashes) String() string { return proto.CompactTextString(m) }
func (*TxSigHashes) ProtoMessage()    {}
func (*TxSigHashes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ecd772f6c7ffacf, []int{4}
}

func (m *TxSigHashes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxSigHashes.Unmarshal(m, b)
}
func (m *TxSigHashes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxSigHashes.Marshal(b, m, deterministic)
}
func (m *TxSigHashes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxSigHashes.Merge(m, src)
}
func (m *TxSigHashes) XXX_Size() int {
	return xxx_messageInfo_TxSigHashes.Size(m)
}
func (m *TxSigHashes) XXX_DiscardUnknown() {
	xxx_messageInfo_TxSigHashes.DiscardUnknown(m)
}

var xxx_messageInfo_TxSigHashes proto.InternalMessageInfo

func (m *TxSigHashes) GetHashPrevOuts() []byte {
	if m != nil {
		return m.HashPrevOuts
	}
	return nil
}

func (m *TxSigHashes) GetHashSequence() []byte {
	if m != nil {
		return m.HashSequence
	}
	return nil
}

func (m *TxSigHashes) GetHashOutputs() []byte {
	if m != nil {
		return m.HashOutputs
	}
	return nil
}

type SignReq struct {
	/// The raw bytes of the transaction to be signed.
	RawTxBytes []byte `protobuf:"bytes,1,opt,name=raw_tx_bytes,json=rawTxBytes,proto3" json:"raw_tx_bytes,omitempty"`
	/// A set of sign descriptors, for each input to be signed.
	SignDescs []*SignDescriptor `protobuf:"bytes,2,rep,name=sign_descs,json=signDescs,proto3" json:"sign_descs,omitempty"`
	//*
	//The pre-computed sighash midstate to be used when generating the final
	//sighash for signing.
	SigHashes            *TxSigHashes `protobuf:"bytes,3,opt,name=sig_hashes,json=sigHashes,proto3" json:"sig_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SignReq) Reset()         { *m = SignReq{} }
func (m *SignReq) String() string { return proto.CompactTextString(m) }
func (*SignReq) ProtoMessage()    {}
func (*SignReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ecd772f6c7ffacf, []int{5}
}

func (m *SignReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignReq.Unmarshal(m, b)
}
func (m *SignReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignReq.Marshal(b, m, deterministic)
}
func (m *SignReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignReq.Merge(m, src)
}
func (m *SignReq) XXX_Size() int {
	return xxx_messageInfo_SignReq.Size(m)
}
func (m *SignReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignReq proto.InternalMessageInfo

func (m *SignReq) GetRawTxBytes() []byte {
	if m != nil {
		return m.RawTxBytes
	}
	return nil
}

func (m *SignReq) GetSignDescs() []*SignDescriptor {
	if m != nil {
		return m.SignDescs
	}
	return nil
}

func (m *SignReq) GetSigHashes() *TxSigHashes {
	if m != nil {
		return m.SigHashes
	}
	return nil
}

type SignResp struct {
	//*
	//A set of signatures realized in a fixed 64-byte format ordered in ascending
	//input order.
	RawSigs [][]byte `protobuf:"bytes,1,rep,name=raw_sigs,json=rawSigs,proto3" json:"raw_sigs,omitempty"`
	//*
	//The pre-computed sighash midstate to be used when generating the final
	//sighash for signing.
	SigHashes            *TxSigHashes `protobuf:"bytes,2,opt,name=sig_hashes,json=sigHashes,proto3" json:"sig_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SignResp) Reset()         { *m = SignResp{} }
func (m *SignResp) String() string { return proto.CompactTextString(m) }
func (*SignResp) ProtoMessage()    {}
func (*SignResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ecd772f6c7ffacf, []int{6}
}

func (m *SignResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignResp.Unmarshal(m, b)
}
func (m *SignResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignResp.Marshal(b, m, deterministic)
}
func (m *SignResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignResp.Merge(m, src)
}
func (m *SignResp) XXX_Size() int {
	return xxx_messageInfo_SignResp.Size(m)
}
func (m *SignResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignResp.DiscardUnknown(m)
}

var xxx_messageInfo_SignResp proto.InternalMessageInfo

func (m *SignResp) GetRawSigs() [][]byte {
	if m != nil {
		return m.RawSigs
	}
	return nil
}

func (m *SignResp) GetSigHashes() *TxSigHashes {
	if m != nil {
		return m.SigHashes
	}
	return nil
}

type InputScript struct {
	/// The serializes witness stack for the specified input.
	Witness [][]byte `protobuf:"bytes,1,rep,name=witness,proto3" json:"witness,omitempty"`
	//**
	//The optional sig script for the specified witness that will only be set if
	//the input specified is a nested p2sh witness program.
	SigScript            []byte   `protobuf:"bytes,2,opt,name=sig_script,json=sigScript,proto3" json:"sig_script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputScript) Reset()         { *m = InputScript{} }
func (m *InputScript) String() string { return proto.CompactTextString(m) }
func (*InputScript) ProtoMessage()    {}
func (*InputScript) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ecd772f6c7ffacf, []int{7}
}

func (m *InputScript) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputScript.Unmarshal(m, b)
}
func (m *InputScript) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputScript.Marshal(b, m, deterministic)
}
func (m *InputScript) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputScript.Merge(m, src)
}
func (m *InputScript) XXX_Size() int {
	return xxx_messageInfo_InputScript.Size(m)
}
func (m *InputScript) XXX_DiscardUnknown() {
	xxx_messageInfo_InputScript.DiscardUnknown(m)
}

var xxx_messageInfo_InputScript proto.InternalMessageInfo

func (m *InputScript) GetWitness() [][]byte {
	if m != nil {
		return m.Witness
	}
	return nil
}

func (m *InputScript) GetSigScript() []byte {
	if m != nil {
		return m.SigScript
	}
	return nil
}

type InputScriptResp struct {
	/// The set of fully valid input scripts requested.
	InputScripts []*InputScript `protobuf:"bytes,1,rep,name=input_scripts,json=inputScripts,proto3" json:"input_scripts,omitempty"`
	//*
	//The pre-computed sighash midstate to be used when generating the final
	//sighash for signing.
	SigHashes            *TxSigHashes `protobuf:"bytes,3,opt,name=sig_hashes,json=sigHashes,proto3" json:"sig_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InputScriptResp) Reset()         { *m = InputScriptResp{} }
func (m *InputScriptResp) String() string { return proto.CompactTextString(m) }
func (*InputScriptResp) ProtoMessage()    {}
func (*InputScriptResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ecd772f6c7ffacf, []int{8}
}

func (m *InputScriptResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputScriptResp.Unmarshal(m, b)
}
func (m *InputScriptResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputScriptResp.Marshal(b, m, deterministic)
}
func (m *InputScriptResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputScriptResp.Merge(m, src)
}
func (m *InputScriptResp) XXX_Size() int {
	return xxx_messageInfo_InputScriptResp.Size(m)
}
func (m *InputScriptResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InputScriptResp.DiscardUnknown(m)
}

var xxx_messageInfo_InputScriptResp proto.InternalMessageInfo

func (m *InputScriptResp) GetInputScripts() []*InputScript {
	if m != nil {
		return m.InputScripts
	}
	return nil
}

func (m *InputScriptResp) GetSigHashes() *TxSigHashes {
	if m != nil {
		return m.SigHashes
	}
	return nil
}

func init() {
	proto.RegisterType((*KeyLocator)(nil), "signrpc.KeyLocator")
	proto.RegisterType((*KeyDescriptor)(nil), "signrpc.KeyDescriptor")
	proto.RegisterType((*TxOut)(nil), "signrpc.TxOut")
	proto.RegisterType((*SignDescriptor)(nil), "signrpc.SignDescriptor")
	proto.RegisterType((*TxSigHashes)(nil), "signrpc.TxSigHashes")
	proto.RegisterType((*SignReq)(nil), "signrpc.SignReq")
	proto.RegisterType((*SignResp)(nil), "signrpc.SignResp")
	proto.RegisterType((*InputScript)(nil), "signrpc.InputScript")
	proto.RegisterType((*InputScriptResp)(nil), "signrpc.InputScriptResp")
}

func init() { proto.RegisterFile("signrpc/signer.proto", fileDescriptor_4ecd772f6c7ffacf) }

var fileDescriptor_4ecd772f6c7ffacf = []byte{
	// 655 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x55, 0x12, 0xf2, 0xd1, 0xb1, 0x1d, 0x60, 0xa9, 0xc0, 0x80, 0x10, 0xc1, 0x7c, 0x28, 0x07,
	0x48, 0x44, 0x8a, 0x90, 0xe0, 0x84, 0x0a, 0xaa, 0x5a, 0x15, 0xa9, 0xc8, 0xc9, 0xa9, 0x17, 0xcb,
	0x71, 0x16, 0x67, 0x65, 0xd7, 0x76, 0xbd, 0xeb, 0x3a, 0x16, 0x17, 0xf8, 0x0d, 0x5c, 0xf8, 0xb9,
	0x68, 0x76, 0x37, 0x89, 0x53, 0x38, 0x20, 0x4e, 0xde, 0x79, 0x3b, 0xf3, 0xf6, 0xed, 0xbc, 0xf1,
	0xc2, 0x3e, 0x67, 0x61, 0x92, 0x67, 0xc1, 0x18, 0xbf, 0x34, 0x1f, 0x65, 0x79, 0x2a, 0x52, 0xd2,
	0xd5, 0xa8, 0x73, 0x0c, 0x70, 0x4a, 0xab, 0xcf, 0x69, 0xe0, 0x8b, 0x34, 0x27, 0x8f, 0x00, 0x22,
	0x5a, 0x79, 0x5f, 0xfd, 0x0b, 0x16, 0x57, 0x76, 0x63, 0xd0, 0x18, 0xb6, 0xdd, 0xbd, 0x88, 0x56,
	0x47, 0x12, 0x20, 0x0f, 0x01, 0x03, 0x8f, 0x25, 0x0b, 0xba, 0xb2, 0x9b, 0x72, 0xb7, 0x17, 0xd1,
	0xea, 0x04, 0x63, 0xc7, 0x07, 0xeb, 0x94, 0x56, 0x9f, 0x28, 0x0f, 0x72, 0x96, 0x21, 0x99, 0x03,
	0x56, 0xee, 0x97, 0x1e, 0x56, 0xcc, 0x2b, 0x41, 0xb9, 0xe4, 0x33, 0x5d, 0x23, 0xf7, 0xcb, 0x53,
	0x5a, 0x1d, 0x22, 0x44, 0x5e, 0x42, 0x17, 0xf7, 0xe3, 0x34, 0x90, 0x7c, 0xc6, 0xe4, 0xce, 0x48,
	0x2b, 0x1b, 0x6d, 0x65, 0xb9, 0x9d, 0x48, 0xae, 0x9d, 0xf7, 0xd0, 0x9e, 0xad, 0xce, 0x0a, 0x41,
	0xf6, 0xa1, 0x7d, 0xe5, 0xc7, 0x05, 0x95, 0x94, 0x2d, 0x57, 0x05, 0x28, 0x2f, 0x8b, 0x3c, 0x75,
	0xbe, 0xa4, 0x33, 0xdd, 0x5e, 0x16, 0x4d, 0x65, 0xec, 0xfc, 0x6c, 0x42, 0x7f, 0xca, 0xc2, 0xa4,
	0x26, 0xf0, 0x35, 0xa0, 0x7a, 0x6f, 0x41, 0x79, 0x20, 0x89, 0x8c, 0xc9, 0xdd, 0xfa, 0xe9, 0xdb,
	0x4c, 0x17, 0x45, 0x62, 0x48, 0x9e, 0x80, 0xc9, 0x59, 0x12, 0xc6, 0xd4, 0x13, 0x25, 0xf5, 0x23,
	0x7d, 0x8a, 0xa1, 0xb0, 0x19, 0x42, 0x98, 0xb2, 0x48, 0x8b, 0xf9, 0x26, 0xa5, 0xa5, 0x52, 0x14,
	0xa6, 0x52, 0x9e, 0x43, 0xbf, 0x64, 0x22, 0xa1, 0x9c, 0xaf, 0xd5, 0xde, 0x90, 0x49, 0x96, 0x46,
	0x95, 0x64, 0xf2, 0x02, 0x3a, 0x69, 0x21, 0xb2, 0x42, 0xd8, 0x6d, 0xa9, 0xae, 0xbf, 0x51, 0x27,
	0xbb, 0xe0, 0xea, 0x5d, 0x62, 0x03, 0xda, 0xb9, 0xf4, 0xf9, 0xd2, 0xee, 0x0e, 0x1a, 0x43, 0xcb,
	0x5d, 0x87, 0xe4, 0x31, 0x18, 0x2c, 0xc9, 0x0a, 0xa1, 0x2d, 0xeb, 0x49, 0xcb, 0x40, 0x42, 0xca,
	0xb4, 0x6f, 0x60, 0xcc, 0x56, 0x53, 0x16, 0x1e, 0xfb, 0x7c, 0x49, 0x39, 0x79, 0x06, 0x7d, 0xac,
	0xf3, 0xb2, 0x9c, 0x5e, 0x79, 0x69, 0x21, 0xd6, 0x9e, 0x99, 0x88, 0x7e, 0xc9, 0xe9, 0xd5, 0x59,
	0x21, 0x38, 0x79, 0x0a, 0x96, 0xcc, 0xe2, 0xf4, 0xb2, 0xa0, 0x49, 0x40, 0x75, 0x17, 0x64, 0xd2,
	0x54, 0x63, 0xd8, 0x06, 0x99, 0xa4, 0x34, 0xf2, 0x75, 0x1b, 0x10, 0x3b, 0x53, 0x90, 0xf3, 0xab,
	0x01, 0x5d, 0xb4, 0xc4, 0xa5, 0x97, 0x64, 0x00, 0x26, 0x0e, 0x8b, 0x58, 0xed, 0xcc, 0x0a, 0xe4,
	0x7e, 0x39, 0x5b, 0xa9, 0x51, 0x79, 0x0b, 0x80, 0xd7, 0x97, 0x76, 0x71, 0xbb, 0x39, 0x68, 0x0d,
	0x8d, 0xc9, 0xbd, 0x4d, 0x47, 0x76, 0xad, 0x75, 0xf7, 0xb8, 0x8e, 0x39, 0x39, 0x90, 0x75, 0xde,
	0x52, 0xde, 0x50, 0xca, 0x30, 0x26, 0xfb, 0xb5, 0x4e, 0x6e, 0x6e, 0x2f, 0x8b, 0xd4, 0xd2, 0x39,
	0x87, 0x9e, 0x52, 0xc6, 0x33, 0x72, 0x1f, 0x7a, 0x28, 0x8d, 0xb3, 0x10, 0x65, 0xb5, 0x86, 0xa6,
	0xdb, 0xcd, 0xfd, 0x72, 0xca, 0xc2, 0xeb, 0xdc, 0xcd, 0x7f, 0xe3, 0x3e, 0x02, 0xe3, 0x04, 0x1d,
	0xd0, 0x2e, 0xdb, 0xd0, 0xd5, 0xb6, 0xaf, 0xd9, 0x75, 0x88, 0x7f, 0x23, 0xb2, 0xef, 0x0c, 0x34,
	0xf2, 0xe8, 0x89, 0xfe, 0xd1, 0x80, 0x9b, 0x35, 0x22, 0xa9, 0xf5, 0x1d, 0x58, 0xca, 0x70, 0x55,
	0xa4, 0x28, 0xeb, 0x9a, 0xea, 0x05, 0x26, 0xdb, 0x06, 0xff, 0xd7, 0xa7, 0xc9, 0xf7, 0x06, 0x74,
	0xa6, 0xf2, 0x61, 0x21, 0x6f, 0xc0, 0xc2, 0x95, 0x32, 0xd7, 0xf5, 0x4b, 0x72, 0x6b, 0xc7, 0x1c,
	0x97, 0x5e, 0x3e, 0xb8, 0x7d, 0x0d, 0xe1, 0x19, 0xf9, 0x00, 0xe4, 0x63, 0x7a, 0x91, 0x15, 0x82,
	0xd6, 0x7b, 0xf2, 0x67, 0xa9, 0xfd, 0xd7, 0x1b, 0x50, 0x9e, 0x1d, 0x8e, 0xcf, 0x5f, 0x85, 0x4c,
	0x2c, 0x8b, 0xf9, 0x28, 0x48, 0x2f, 0xc6, 0x31, 0x0b, 0x97, 0x22, 0x61, 0x49, 0x98, 0x50, 0x51,
	0xa6, 0x79, 0x34, 0x8e, 0x93, 0xc5, 0x38, 0xde, 0x3c, 0x80, 0x79, 0x16, 0xcc, 0x3b, 0xf2, 0x09,
	0x3c, 0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x86, 0xbd, 0x64, 0x1a, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SignerClient is the client API for Signer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SignerClient interface {
	//*
	//SignOutputRaw is a method that can be used to generated a signature for a
	//set of inputs/outputs to a transaction. Each request specifies details
	//concerning how the outputs should be signed, which keys they should be
	//signed with, and also any optional tweaks. The return value is a fixed
	//64-byte signature (the same format as we use on the wire in Lightning).
	//
	//If we are  unable to sign using the specified keys, then an error will be
	//returned.
	SignOutputRaw(ctx context.Context, in *SignReq, opts ...grpc.CallOption) (*SignResp, error)
	//*
	//ComputeInputScript generates a complete InputIndex for the passed
	//transaction with the signature as defined within the passed SignDescriptor.
	//This method should be capable of generating the proper input script for
	//both regular p2wkh output and p2wkh outputs nested within a regular p2sh
	//output.
	//
	//Note that when using this method to sign inputs belonging to the wallet,
	//the only items of the SignDescriptor that need to be populated are pkScript
	//in the TxOut field, the value in that same field, and finally the input
	//index.
	ComputeInputScript(ctx context.Context, in *SignReq, opts ...grpc.CallOption) (*InputScriptResp, error)
}

type signerClient struct {
	cc *grpc.ClientConn
}

func NewSignerClient(cc *grpc.ClientConn) SignerClient {
	return &signerClient{cc}
}

func (c *signerClient) SignOutputRaw(ctx context.Context, in *SignReq, opts ...grpc.CallOption) (*SignResp, error) {
	out := new(SignResp)
	err := c.cc.Invoke(ctx, "/signrpc.Signer/SignOutputRaw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerClient) ComputeInputScript(ctx context.Context, in *SignReq, opts ...grpc.CallOption) (*InputScriptResp, error) {
	out := new(InputScriptResp)
	err := c.cc.Invoke(ctx, "/signrpc.Signer/ComputeInputScript", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignerServer is the server API for Signer service.
type SignerServer interface {
	//*
	//SignOutputRaw is a method that can be used to generated a signature for a
	//set of inputs/outputs to a transaction. Each request specifies details
	//concerning how the outputs should be signed, which keys they should be
	//signed with, and also any optional tweaks. The return value is a fixed
	//64-byte signature (the same format as we use on the wire in Lightning).
	//
	//If we are  unable to sign using the specified keys, then an error will be
	//returned.
	SignOutputRaw(context.Context, *SignReq) (*SignResp, error)
	//*
	//ComputeInputScript generates a complete InputIndex for the passed
	//transaction with the signature as defined within the passed SignDescriptor.
	//This method should be capable of generating the proper input script for
	//both regular p2wkh output and p2wkh outputs nested within a regular p2sh
	//output.
	//
	//Note that when using this method to sign inputs belonging to the wallet,
	//the only items of the SignDescriptor that need to be populated are pkScript
	//in the TxOut field, the value in that same field, and finally the input
	//index.
	ComputeInputScript(context.Context, *SignReq) (*InputScriptResp, error)
}

// UnimplementedSignerServer can be embedded to have forward compatible implementations.
type UnimplementedSignerServer struct {
}

func (*UnimplementedSignerServer) SignOutputRaw(ctx context.Context, req *SignReq) (*SignResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignOutputRaw not implemented")
}
func (*UnimplementedSignerServer) ComputeInputScript(ctx context.Context, req *SignReq) (*InputScriptResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeInputScript not implemented")
}

func RegisterSignerServer(s *grpc.Server, srv SignerServer) {
	s.RegisterService(&_Signer_serviceDesc, srv)
}

func _Signer_SignOutputRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServer).SignOutputRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/signrpc.Signer/SignOutputRaw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServer).SignOutputRaw(ctx, req.(*SignReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signer_ComputeInputScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServer).ComputeInputScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/signrpc.Signer/ComputeInputScript",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServer).ComputeInputScript(ctx, req.(*SignReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Signer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "signrpc.Signer",
	HandlerType: (*SignerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignOutputRaw",
			Handler:    _Signer_SignOutputRaw_Handler,
		},
		{
			MethodName: "ComputeInputScript",
			Handler:    _Signer_ComputeInputScript_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "signrpc/signer.proto",
}
